FORMAT: 1A
HOST: http://www.google.com

# Publero API
Notes API is a *short texts saving* service similar to its physical paper presence on your table.

# Group Publisher Admin
Publisher related links

## Publisher Collection [/admin/publisher]

### List of All Publishers [GET]
+ Request

    + Header
    
                Authorization: Bearer {api_key}

+ Response 200 (application/json)

        [
            {
                "name": "Publisher 1",
                "description": "Publisher 1 description",
                "contacts": [
                    {
                        "type": "email",
                        "title": "Personal email",
                        "description": "Email description",
                        "body": "some_email@example.com"
                    },
                    {
                        "type": "address",
                        "title": "Home Address",
                        "description": "Address description",
                        "body": "Some Street 5554, 555 21 Some City"
                    },
                    ...
                ]
            },
            {
                "name": "Publisher 2",
                "description": "Publisher 2 description",
                "contacts": [
                    {
                        "type": "email",
                        "title": "Personal email",
                        "description": "Email description",
                        "body": "some_email@example.com"
                    },
                    {
                        "type": "address",
                        "title": "Home Address",
                        "description": "Address description",
                        "body": "Some Street 5554, 555 21 Some City"
                    },
                    ...
                ]
            },
            ...
        ]

### Create Publisher [POST]
+ Request (application/json)

    + Header
    
                Authorization: Bearer {api_key}
        
    + Body
        
                {
                    "name": "Publisher 1",
                    "description": "Publisher 1 description",
                    "contacts": [
                        {
                            "type": "email",
                            "title": "Personal email",
                            "description": "Email description",
                            "body": "some_email@example.com"
                        },
                        {
                            "type": "address",
                            "title": "Home Address",
                            "description": "Address description",
                            "body": "Some Street 5554, 555 21 Some City"
                        },
                        ...
                    ]
                }

+ Response 200 (application/json)

        {
          "id": 1,
          "uri": "/publisher/1"
        }
        
## Publisher [/admin/publisher/{id}]        
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Publisher to perform action with. Has example value.

### Read [GET]
+ Request

    + Header
    
                Authorization: Bearer {api_key}
        
+ Response 200 (application/json)

        {
            "name": "Publisher 1",
            "description": "Publisher 1 description",
            "contacts": [
                {
                    "type": "email",
                    "title": "Personal email",
                    "description": "Email description",
                    "body": "some_email@example.com"
                },
                {
                    "type": "address",
                    "title": "Home Address",
                    "description": "Address description",
                    "body": "Some Street 5554, 555 21 Some City"
                },
                ...
            ]

        }
        
### Full Update [PUT]
+ Request

    + Header
    
                Authorization: Bearer {api_key}
                
+ Response 204


### Partial Update [PATCH]
+ Request

    + Header
    
                Authorization: Bearer {api_key}

+ Response 204

        
### Delete [DELETE]
+ Request

    + Header
    
                Authorization: Bearer {api_key}

+ Response 204
