FORMAT: 1A
HOST: http://www.google.com

# Publero API

#### Authorization
To authenticate against the API, client must provide access token in 1 of 3 ways:

- `Authorization` HTTP header in form `Authorization: Token {token}`

- `access_token` query parameter

- `access_token` POST parameter - only for `application/x-www-form-urlencoded` request

Authorization HTTP header is the preferred option.

If authorization fails, status code 403 (Forbidden) is returned automatically with the following response:

```json
{
    "code":403,
    "message":"Access Denied",
     "errors":null
}
```

#### Request fail

If the call was unsuccessful it will return status code 400 (Bad request) and response containing fields (error response):

 - `code` - status code
 
 - `message` - error message (e.g. "Validation Failed")
 
 - `errors` - list of errors


# Group Admin - Publisher
Publisher related links

## Publisher Collection [/admin/publisher]

### List of All Publishers [GET]
+ Request

    + Header
    
                Authorization: Token {token}

+ Response 200 (application/json)

        [
            {
                "name": "Publisher 1",
                "description": "Publisher 1 description",
                "contacts": [
                    {
                        "type": "email",
                        "title": "Personal email",
                        "description": "Email description",
                        "body": "some_email@example.com"
                    },
                    {
                        "type": "address",
                        "title": "Home Address",
                        "description": "Address description",
                        "body": "Some Street 5554, 555 21 Some City"
                    }
                ]
            },
            {
                "name": "Publisher 2",
                "description": "Publisher 2 description",
                "contacts": [
                    {
                        "type": "email",
                        "title": "Personal email",
                        "description": "Email description",
                        "body": "some_email@example.com"
                    },
                    {
                        "type": "address",
                        "title": "Home Address",
                        "description": "Address description",
                        "body": "Some Street 5554, 555 21 Some City"
                    }
                ]
            }
        ]

### Create Publisher [POST]
+ Request (application/json)

    + Header
    
                Authorization: Token {token}
        
    + Body
        
                {
                    "name": "Publisher 1",
                    "description": "Publisher 1 description",
                    "contacts": [
                        {
                            "type": "email",
                            "title": "Personal email",
                            "description": "Email description",
                            "body": "some_email@example.com"
                        },
                        {
                            "type": "address",
                            "title": "Home Address",
                            "description": "Address description",
                            "body": "Some Street 5554, 555 21 Some City"
                        }
                    ]
                }

+ Response 201 (application/json)

        {
          "id": 1,
          "uri": "/publisher/1"
        }
        
## Publisher [/admin/publisher/{id}]        
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Publisher to perform action with. Has example value.

### Read [GET]
+ Request

    + Header
    
                Authorization: Token {token}
        
+ Response 200 (application/json)

        {
            "name": "Publisher 1",
            "description": "Publisher 1 description",
            "contacts": [
                {
                    "type": "email",
                    "title": "Personal email",
                    "description": "Email description",
                    "body": "some_email@example.com"
                },
                {
                    "type": "address",
                    "title": "Home Address",
                    "description": "Address description",
                    "body": "Some Street 5554, 555 21 Some City"
                }
            ]

        }
        
### Full Update [PUT]
+ Request (application/json)

    + Header
    
                Authorization: Token {token}
                
    + Body
    
                {
                    "name": "Publisher 1",
                    "description": "Publisher 1 description",
                    "contacts": [
                        {
                            "type": "email",
                            "title": "Personal email",
                            "description": "Email description",
                            "body": "some_email@example.com"
                        },
                        {
                            "type": "address",
                            "title": "Home Address",
                            "description": "Address description",
                            "body": "Some Street 5554, 555 21 Some City"
                        }
                    ]
                }    
                
+ Response 204


### Partial Update [PATCH]
+ Request (application/json)

    + Header
    
                Authorization: Token {token}
            
    + Body
    
                {
                    "name": "Publisher 1",
                    "description": "Publisher 1 description",
                    "contacts": [
                        {
                            "type": "email",
                            "title": "Personal email",
                            "description": "Email description",
                            "body": "some_email@example.com"
                        },
                        {
                            "type": "address",
                            "title": "Home Address",
                            "description": "Address description",
                            "body": "Some Street 5554, 555 21 Some City"
                        }
                    ]
                }    

+ Response 204

        
### Delete [DELETE]
+ Request

    + Header
    
                Authorization: Token {token}

+ Response 204

# Group Admin - Seller
Seller related links

## Seller Collection [/admin/seller]

### List of All Sellers [GET]
+ Request

    + Header
    
                Authorization: Token {token}

+ Response 200 (application/json)

        [
            {
                "name": "seller 1",
                "contacts": [
                    {
                        "type": "email",
                        "title": "Personal email",
                        "description": "Email description",
                        "body": "some_email@example.com"
                    },
                    {
                        "type": "address",
                        "title": "Home Address",
                        "description": "Address description",
                        "body": "Some Street 5554, 555 21 Some City"
                    }
                ],
                "identification": "11111111",
                "vatNumber": "CZ11111111"
            },
            {
                "name": "seller 2",
                "contacts": [
                    {
                        "type": "email",
                        "title": "Personal email",
                        "description": "Email description",
                        "body": "some_email@example.com"
                    },
                    {
                        "type": "address",
                        "title": "Home Address",
                        "description": "Address description",
                        "body": "Some Street 5554, 555 21 Some City"
                    }
                ],
                "identification": "22222222
                "vatNumber": "CZ22222222"
            }
        ]

### Create Seller [POST]
+ Request (application/json)

    + Header
    
                Authorization: Token {token}
        
    + Body
        
                {
                    "name": "Seller 1",
                    "contacts": [
                        {
                            "type": "email",
                            "title": "Personal email",
                            "description": "Email description",
                            "body": "some_email@example.com"
                        },
                        {
                            "type": "address",
                            "title": "Home Address",
                            "description": "Address description",
                            "body": "Some Street 5554, 555 21 Some City"
                        }
                    ],
                    "identification": "11111111",
                    "vatNumber": "CZ11111111"
                }

+ Response 201 (application/json)

        {
          "id": 1,
          "uri": "/seller/1"
        }
        
## Seller [/admin/seller/{id}]        
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the seller to perform action with. Has example value.

### Read [GET]
+ Request

    + Header
    
                Authorization: Token {token}
        
+ Response 200 (application/json)

        {
            "name": "Seller 1",
            "contacts": [
                {
                    "type": "email",
                    "title": "Personal email",
                    "description": "Email description",
                    "body": "some_email@example.com"
                },
                {
                    "type": "address",
                    "title": "Home Address",
                    "description": "Address description",
                    "body": "Some Street 5554, 555 21 Some City"
                }
            ],
            "identification": "11111111",
            "vatNumber": "CZ11111111"
        }
        
### Full Update [PUT]
+ Request (application/json)

    + Header
    
                Authorization: Token {token}
                
    + Body

                {
                    "name": "Seller 1",
                    "contacts": [
                        {
                            "type": "email",
                            "title": "Personal email",
                            "description": "Email description",
                            "body": "some_email@example.com"
                        },
                        {
                            "type": "address",
                            "title": "Home Address",
                            "description": "Address description",
                            "body": "Some Street 5554, 555 21 Some City"
                        }
                    ],
                    "identification": "11111111",
                    "vatNumber": "CZ11111111"
                }

+ Response 204


### Partial Update [PATCH]
+ Request (application/json)

    + Header
    
                Authorization: Token {token}
                
    + Body
    
                {
                    "name": "Seller 1",
                    "contacts": [
                        {
                            "type": "email",
                            "title": "Personal email",
                            "description": "Email description",
                            "body": "some_email@example.com"
                        },
                        {
                            "type": "address",
                            "title": "Home Address",
                            "description": "Address description",
                            "body": "Some Street 5554, 555 21 Some City"
                        }
                    ],
                    "identification": "11111111",
                    "vatNumber": "CZ11111111"
                }

+ Response 204

        
### Delete [DELETE]
+ Request

    + Header
    
                Authorization: Token {token}

+ Response 204

# Group Admin - Document
Document links

## Document API [/admin/document/{id}]

### Retrieve document [GET]
+ Request

    + Header
    
                Authorization: Token {token}

+ Response 200 (application/octet-stream)

    + Body

                {binary_data}
                
# Group User - Library
Document links

## Document API [/user/library]

### Retrieve user library [GET]
+ Request

    + Header
    
                Authorization: Token {token}

+ Response 200 (application/json)

    + Body

                [
                    {
                        "id": "1",
                        "name": "Product 1",
                        "slug": "product_1",
                        "imageUrl": "/product/image/1",
                        "prices": [],
                        "packages": [],
                        "productType": "article",
                        "document" : "",
                        "perex": "Article 1 Perex",
                        "author": { "id": "1", "uri": "/user/1" }
                    },
                    {
                        "id": "2",
                        "name": "Product 2",
                        "slug": "product_2",
                        "imageUrl": "",
                        "prices": "",
                        "packages": "",
                        "productType": "attachment",
                        "document" : "",
                        "free": "",
                        "issue": "",
                        "groupItem": ""
                    },
                    {
                        "id": "3",
                        "name": "Product 3",
                        "slug": "product_3",
                        "imageUrl": "",
                        "prices": "",
                        "packages": "",
                        "productType": "issue",
                        "document" : "",
                        "publishedAt": "",
                        "autopublish": "",
                        "free": "",
                        "printable": "",
                        "downloadable": "",
                        "identification": "",
                        "attachments": "",
                        "publisher": "",
                        "title": "",
                        "slug": ""
                    },
                    {
                        "id": "4",
                        "name": "Product 4",
                        "slug": "product_4",
                        "imageUrl": "",
                        "prices": "",
                        "packages": "",
                        "productType": "UserDocument",
                        "document" : "",
                        "owner": "",
                        "private": ""           
                    }
                ]

# Group Admin - Title

## Title [/admin/content/title]

### Create Title [POST]
+ Request (application/json)

    + Header
    
                Authorization: Token {token}
        
    + Body
    
                {
                    "type":"title",
                    "name":"test_title",
                    "publisherName":"test_publisher",
                    "description":"",
                    "identification":"",
                    "issueDefaultPrice":120,
                    "defaultPrice":120,
                    "issueDefaultAppstoreTier":10,
                    "issueDefaultPrintable":true,
                    "issueDefaultDownloadable":true,
                    "free":true,
                    "language":"cs",
                    "categories": [
                        {
                            "category":"test_category_1",
                            "default":true
                        }
                    ],
                    "tags":["test_book"],
                    "publisher":1
                }
+ Response 201 (application/json)

            {
                "id": 1,
                "uri": "content/title/1"
            }

## Title [/admin/content/title/{id}]  
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Title to perform action with. Has example value.

### Read [GET]
+ Request

    + Header
    
                Authorization: Token {token}

+ Response 200 (application/json)
    
        {
            "id":1,
            "name":"read",
            "defaultPrice":15,
            "free":false,
            "publisherName":"Test publisher",
            "categories": [
                {
                    "category": [
                        "name":"Test category 1"
                    ]
                }
            ],
            "groups": [
                {
                    "id":1,
                    "uri":"content/group/1"
                }
            ],
            "issues": [
                {
                    "id":1,
                    "uri":"content/issue/1"
                }
            ],
            "publisher": [
                "id":1,
                "uri":"content/publisher/1"
            ],
            "issueDefaultPrice":120,
            "defaultPrice":120,
            "issueDefaultAppstoreTier":10,
            "issueDefaultPrintable":true,
            "issueDefaultDownloadable":true,
            "language":"cs",
            "description":"",
            "identification":"",
            "tags": [
                "test tag"
            ]
        }

### Full Update [PUT]
+ Request (application/json)

    + Header
    
                Authorization: Token {token}
                
    + Body
    
               {
                    "type":"title",
                    "name":"test_title",
                    "publisherName":"test_publisher",
                    "description":"",
                    "identification":"",
                    "issueDefaultPrice":120,
                    "defaultPrice":120,
                    "issueDefaultAppstoreTier":10,
                    "issueDefaultPrintable":true,
                    "issueDefaultDownloadable":true,
                    "free":true,
                    "language":"cs",
                    "categories": [
                        {
                            "category":"test_category_1",
                            "default":true
                        }
                    ],
                    "tags":["test_book"],
                    "publisher":1
                }
+ Response 204

### Full Update [PATCH]
+ Request (application/json)

    + Header
    
                Authorization: Token {token}
                
    + Body
    
               {
                    "type":"title",
                    "name":"test_title",
                    "publisherName":"test_publisher",
                    "description":"",
                    "identification":"",
                    "issueDefaultPrice":120,
                    "defaultPrice":120,
                    "issueDefaultAppstoreTier":10,
                    "issueDefaultPrintable":true,
                    "issueDefaultDownloadable":true,
                    "free":true,
                    "language":"cs",
                    "categories": [
                        {
                            "category":"test_category_1",
                            "default":true
                        }
                    ],
                    "tags":["test_book"],
                    "publisher":1
                }
+ Response 204

### Delete [DELETE]
+ Request

    + Header
    
                Authorization: Token {token}

+ Response 204



# Group Admin - Issue
Issue related links

## Issue [/admin/content/issue]
### Create Issue [POST]
+ Request (application/json)

    + Header
    
                Authorization: Token {token}
        
    + Body
    
            {
                "name":"test_issue",
                "publishedAt":"2014-01-01 00:00:00",
                "autopublish":true,
                "free":true,
                "printable":true,
                "downloadable":true,
                "identification":"",
                "type":"issue",
                "prices": [
                    {
                        "priceType":"normal",
                        "price":80,
                        "tier":10,
                        "validSince":"2014-01-01 00:00:00",
                        "currency":"CZK"
                    }
                ],
                "publisher":1,
                "title":1,
                "document":2
            }
+ Response 201 (application/json)

            {
                "id": 1,
                "uri": "content/issue/1"
            }

## Issue [/admin/content/issue/{id}]

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Issue to perform action with. Has example value.


### Read [GET]
+ Request

    + Header
    
                Authorization: Token {token}

+ Response 200 (application/json)
    
        {
            "id":7,
            "name":"test_issue",
            "slug":"test-issue-2",
            "imageUrl":"picture.jpg",
            "prices": [
                {
                    "validSince":"2014-01-01 00:00:00",
                    "priceType":"normal",
                    "price":80,
                    "tier":10,
                    "currency":"CZK"
                }
            ],
            "document": [
                "id":2,
                "uri":"content/document/2"
            ],
            "publishedAt":"2014-01-01 00:00:00",
            "autopublish":true,
            "free":true,
            "printable":true,
            "downloadable":true,
            "identification":"978-80-7462-066-9",
            "attachments":[],
            "publisher": [
                "id":1,
                "uri":"content/publisher/1"
            ],
            "title":[
                "id":1,
                "uri":"content/title/1"
            ]
        }



### Full Update [PUT]
+ Request (application/json)

    + Header
    
                Authorization: Token {token}
                
    + Body
    
            {
                "name":"test_issue",
                "publishedAt":"2014-01-01 00:00:00",
                "autopublish":true,
                "free":true,
                "printable":true,
                "downloadable":true,
                "identification":"",
                "type":"issue",
                "prices": [
                    {
                        "priceType":"normal",
                        "price":80,
                        "tier":10,
                        "validSince":"2014-01-01 00:00:00",
                        "currency":"CZK"
                    }
                ],
                "publisher":1,
                "title":1,
                "document":2
            }
+ Response 204

### Full Update [PATCH]
+ Request (application/json)

    + Header
    
                Authorization: Token {token}
                
    + Body
    
            {
                "name":"test_issue",
                "publishedAt":"2014-01-01 00:00:00",
                "autopublish":true,
                "free":true,
                "printable":true,
                "downloadable":true,
                "identification":"",
                "type":"issue",
                "prices": [
                    {
                        "priceType":"normal",
                        "price":80,
                        "tier":10,
                        "validSince":"2014-01-01 00:00:00",
                        "currency":"CZK"
                    }
                ],
                "publisher":1,
                "title":1,
                "document":2
            }

+ Response 204

### Delete [DELETE]
+ Request

    + Header
    
                Authorization: Token {token}

+ Response 204

# Group Admin  -  Document

## Document [/admin/content/document]
### Create Document [POST]
+ Request (application/json)

    + Header
    
                Authorization: Token {token}
        
    + Body
    
            {
                "type":"pdf",
                "name":"test_document_create",
           
            }
+ Response 201 (application/json)

            {
                "id": 1,
                "uri": "content/document/1"
            }

### Read [GET]
+ Request

    + Header
    
                Authorization: Token {token}
+ Response 200 (application/json)
    + Body
    
            {
                "name":"test_name",
            }

### Full Update [PUT]
+ Request

    + Header
    
                Authorization: Token {token}

    + Body
    
            {
                "type":"pdf",
                "name":"test_document_create",
            }

+ Response 204

### Full Update [PATCH]
+ Request

    + Header
    
                Authorization: Token {token}

    + Body
    
            {
                "type":"pdf",
                "name":"test_document_create",
            }

+ Response 204

### Delete [DELETE]
+ Request

    + Header
    
                Authorization: Token {token}
+ Response 204
    
# Group Content - Web page

## Document [/admin/content/web_page]
### Create Document [POST]
+ Request (application/json)

    + Header
    
                Authorization: Token {token}
+ Response 201 (application/json)

            {
                "id": 1,
                "uri": "admin/web_page/1"
            }

## Web page [/admin/content/web_page/{id}] 

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Web page to perform action with. Has example value.

### Read [GET]
+ Request

    + Header
    
                Authorization: Token {token}
+ Response 200 (application/json)
    + Body
    
            {
                "name":"test_name",
                "content":"<p>test_content</p>"
            }

### Full Update [PUT]
+ Request

    + Header
    
                Authorization: Token {token}

    + Body
    
            {
                "name":"test_name",
                "content":"<p>test_content</p>"
            }

+ Response 204

### Full Update [PATCH]
+ Request

    + Header
    
                Authorization: Token {token}

    + Body
    
            {
                "name":"test_name",
                "content":"<p>test_content</p>"
            }

+ Response 204

### Delete [DELETE]
+ Request

    + Header
    
                Authorization: Token {token}

+ Response 204

# Group Content - Issue

## Issue [/content/issue/{id}]

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Issue to perform action with. Has example value.


### Read [GET]

+ Response 200 (application/json)
    
        {
            "id":7,
            "name":"test_issue",
            "slug":"test-issue-2",
            "imageUrl":"picture.jpg",
            "prices": [
                {
                    "validSince":"2014-01-01 00:00:00",
                    "priceType":"normal",
                    "price":80,
                    "tier":10,
                    "currency":"CZK"
                }
            ],
            "document": [
                "id":2,
                "uri":"content/document/2"
            ],
            "publishedAt":"2014-01-01 00:00:00",
            "autopublish":true,
            "free":true,
            "printable":true,
            "downloadable":true,
            "identification":"",
            "attachments":[],
            "publisher": [
                "id":1,
                "uri":"content/publisher/1"
            ],
            "title": [
                "id":1,
                "uri":"content/title/1"
            ]
        }


# Group Content - Title

## Title [/content/title/{id}]  
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Title to perform action with. Has example value.

### Read [GET]
+ Response 200 (application/json)
    
        {
            "id":1,
            "name":"read",
            "defaultPrice":15,
            "free":false,
            "publisherName":"Test publisher",
            "categories": [
                {
                    "category": [
                        "name":"Test category 1"
                    ]
                }
            ],
            "groups": [
                {
                    "id":1,
                    "uri":"content/group/1"
                }
            ],
            "issues": [
                {
                    "id":1,
                    "uri":"content/issue/1"
                }
            ],
            "publisher": [
                "id":1,
                "uri":"content/publisher/1"
            ],
            "issueDefaultPrice":120,
            "defaultPrice":120,
            "issueDefaultAppstoreTier":10,
            "issueDefaultPrintable":true,
            "issueDefaultDownloadable":true,
            "language":"cs",
            "description":"",
            "identification":"",
            "tags": [
                "test tag"
            ]
        }

# Group Admin - Group

## Group [/admin/content/group]
### Create Group [POST]
+ Request (application/json)

    + Header
    
                Authorization: Token {token}
        
    + Body
    
            {
                "name":"test_create_group",
                "title":"1",
           
            }
+ Response 201 (application/json)

            {
                "id": 1,
                "uri": "content/group/1"
            }

## Group [/admin/content/group/{id}]  
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Group to perform action with. Has example value.

### Read [GET]

+ Response 200 (application/json)
    
        {
            "id":7,
            "name":"test_name",
            "groupsItems": [
                {
                    "id":1,
                    "uri":"content/group_item/1"
                }
            ]
            
        }

### Full Update [PUT]
+ Request

    + Header
    
                Authorization: Token {token}

    + Body
    
            {
                "name":"test_name",
            }

+ Response 204

### Full Update [PATCH]
+ Request

    + Header
    
                Authorization: Token {token}

    + Body
    
            {
                "name":"test_name",
            }

+ Response 204

### Delete [DELETE]
+ Request

    + Header
    
                Authorization: Token {token}

+ Response 204

# Group Admin - GroupItem

## GroupItem [/admin/content/group_item]
### Create GroupItem [POST]
+ Request (application/json)

    + Header
    
                Authorization: Token {token}
        
    + Body
    
            {
                "name":"test_create_group_item",
                "group":"1",
           
            }
+ Response 201 (application/json)

            {
                "id": 1,
                "uri": "content/group_item/1"
            }

## GroupItem [/admin/content/group_item/{id}]  
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Group item to perform action with. Has example value.

### Read [GET]

+ Response 200 (application/json)
    
        {
            "id":7,
            "name":"test_name",
            "group":"1",
            "attachments": [
                {
                    "id":"1",
                    "uri": "content/attachment/1"
                }
            ]           
        }

### Full Update [PUT]
+ Request

    + Header
    
                Authorization: Token {token}

    + Body
    
            {
                "name":"test_name",
                "group":"1"
            }

+ Response 204

### Full Update [PATCH]
+ Request

    + Header
    
                Authorization: Token {token}

    + Body
    
            {
                "name":"test_name",
                "group":"1"
            }

+ Response 204

### Delete [DELETE]
+ Request

    + Header
    
                Authorization: Token {token}

+ Response 204

# Group Admin - Category

## Category [/admin/content/category]
### Create GroupItem [POST]
+ Request (application/json)

    + Header
    
                Authorization: Token {token}
        
    + Body
    
            {
                "name":"test_create_category",
                "parent":"1",
                "title":"1",        
            }
+ Response 201 (application/json)

            {
                "id": 1,
                "uri": "content/category/1"
            }

## Category [/admin/content/category/{id}]  
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Category to perform action with. Has example value.

### Read [GET]

+ Response 200 (application/json)
    
        {
            "id":7,
            "name":"test_name",
            "code":"test_code",
            "parent":"1",
            "titleToCategories": [
                {
                    "id":1,
                    "uri":"content/category/1"
                },
            ],
            "children": []
            
        }

### Full Update [PUT]
+ Request

    + Header
    
                Authorization: Token {token}

    + Body
    
            {
                "name":"test_name",
                "code":"test_code",
                "parent":"1",
            }

+ Response 204

### Full Update [PATCH]
+ Request

    + Header
    
                Authorization: Token {token}

    + Body
    
            {
                "name":"test_name",
                "code":"test_code",
                "parent":"1",
            }

+ Response 204

### Delete [DELETE]
+ Request

    + Header
    
                Authorization: Token {token}

+ Response 204

# Group Admin - Attachment

## Attachment [/admin/content/attachment]
### Create Group [POST]
+ Request (application/json)

    + Header
    
                Authorization: Token {token}
        
    + Body
    
            {
                "free":true,
                "name":"test_attachment",
                "prices": [
                    {
                        "priceType":"normal",
                        "price":"10",
                        "tier":"10",
                        "validSince":"2014-01-01 10:00:00",
                        "currency":"CZK"          
                    }
                ]
                "issue":"1",
                "groupItem":"1",
                "document":"1"  
            }
+ Response 201 (application/json)

            {
                "id": 1,
                "uri": "content/attachment/1"
            }

## Category [/admin/content/attachment/{id}]  
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Category to perform action with. Has example value.

### Read [GET]
+ Response 200 (application/json)
    
            {
                "free":true,
                "name":"test_attachment",
                "prices": [
                    {
                        "priceType":"normal",
                        "price":"10",
                        "tier":"10",
                        "validSince":"2014-01-01 10:00:00",
                        "currency":"CZK"          
                    }
                ]
                "issue":[
                    "id":1,
                    "uri":"content/publisher/1"
                ],
                "groupItem":[
                    "id":1,
                    "uri":"content/attachment/1"
                ],
                "document":[
                    "id":1,
                    "uri":"content/attachment/1"
                ], 
            }

### Full Update [PUT]
+ Request

    + Header
    
                Authorization: Token {token}

    + Body
    
            {
                "free":true,
                "name":"test_attachment",
                "prices": [
                    {
                        "priceType":"normal",
                        "price":"10",
                        "tier":"10",
                        "validSince":"2014-01-01 10:00:00",
                        "currency":"CZK"          
                    }
                ]
                "issue":"1",
                "groupItem":"1",
                "document":"1"  
            }

+ Response 204

### Full Update [PATCH]
+ Request

    + Header
    
                Authorization: Token {token}

    + Body
    
            {
                "free":true,
                "name":"test_attachment",
                "prices": [
                    {
                        "priceType":"normal",
                        "price":"10",
                        "tier":"10",
                        "validSince":"2014-01-01 10:00:00",
                        "currency":"CZK"          
                    }
                ]
                "issue":"1",
                "groupItem":"1",
                "document":"1"  
            }

+ Response 204

### Delete [DELETE]
+ Request

    + Header
    
                Authorization: Token {token}

+ Response 204

# Group Admin - Voucher

## Voucher [/admin/selling/voucher]
### Create Voucher [POST]
+ Request (application/json)

    + Header
    
                Authorization: Token {token}
        
    + Body
    
            {
                "code":"test_code",
                "validUntil":"2000-01-01 10:10:10",
                "voucherSeries":"8"
            
            }
+ Response 201 (application/json)

            {
                "id": 1,
                "uri": "admin/selling/voucher/1"
            }

## Voucher [/admin/selling/voucher/{id}]  
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Voucher to perform action with. Has example value.

### Read [GET]

+ Response 200 (application/json)
    
        {
            "id":41,
            "code":"test_code",
            "validUntil":"2000-01-01 10:10:10",
            "voucherSeries":[],
            
        }

### Full Update [PUT]
+ Request

    + Header
    
                Authorization: Token {token}

    + Body
    
            {
                "code":"test_code",
                "validUntil":"2000-01-01 10:10:10",
                "voucherSeries":"8"
            
            }

+ Response 204

### Full Update [PATCH]
+ Request

    + Header
    
                Authorization: Token {token}

    + Body
    
            {
                "code":"test_code",
                "validUntil":"2000-01-01 10:10:10",
                "voucherSeries":"8"
            
            }

+ Response 204

### Delete [DELETE]
+ Request

    + Header
    
                Authorization: Token {token}

+ Response 204

# Group Admin - Account

## Account [/admin/selling/account]
### Create Account [POST]
+ Request (application/json)

    + Header
    
                Authorization: Token {token}
        
    + Body
    
            {
                "seller":"14",
                "code":"test_create",
            
            }
+ Response 201 (application/json)

            {
                "id": 1,
                "seller": "admin/selling/seller/1"
                "uri": "admin/selling/voucher/1"
            }

## Account [/admin/selling/account/{id}]  
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Account to perform action with. Has example value.

### Read [GET]

+ Response 200 (application/json)
    
        {
            "id":25,
            "code":"test_create",
            "seller": [
                "admin/selling/seller/1"
            ]            
        }

### Full Update [PUT]
+ Request

    + Header
    
                Authorization: Token {token}

    + Body
    
            {
                "seller":"14",
                "code":"test_create",
            
            }

+ Response 204

### Full Update [PATCH]
+ Request

    + Header
    
                Authorization: Token {token}

    + Body
    
            {
                "seller":"14",
                "code":"test_create",
            
            }
+ Response 204

### Delete [DELETE]
+ Request

    + Header
    
                Authorization: Token {token}
+ Response 204

# Group Admin - Vat
## Vat [/admin/selling/vat]
### Create Vat [POST]
+ Request (application/json)

    + Header
    
                Authorization: Token {token}
        
    + Body
    
            {
                "code": "normal",
                "validSince": "2000-01-01 10:10:10",
                "value": "20"
            
            }
+ Response 201 (application/json)

            {
                "id": 1,
                "uri": "admin/selling/vat/1"
            }

## Vat [/admin/selling/vat/{id}]  
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Vat to perform action with. Has example value.

### Read [GET]

+ Response 200 (application/json)
    
        {
            "id":41,
            "code":"test_code",
            "validSince":"2000-01-01 10:10:10",
            "value": "20"
            
        }

### Full Update [PUT]
+ Request

    + Header
    
                Authorization: Token {token}

    + Body
    
            {
                "code": "normal",
                "validSince": "2000-01-01 10:10:10",
                "value": "20"
            
            }

+ Response 204

### Full Update [PATCH]
+ Request

    + Header
    
                Authorization: Token {token}

    + Body
    
            {
                "code": "normal",
                "validSince": "2000-01-01 10:10:10",
                "value": "20"
            
            }
+ Response 204

### Delete [DELETE]
+ Request

    + Header
    
                Authorization: Token {token}
+ Response 204

# Group Admin - Voucher series
## Vat [/admin/selling/voucher_series]
### Create Vat [POST]
+ Request (application/json)

    + Header
    
                Authorization: Token {token}
        
    + Body
    
            {
                "name": "test_name",
                "codePattern": "AA",
                "vouchersInSeries": "1",
                "usagesPerVoucherLimit": "1",
                "usagesPerUserLimit": "1",
                "userPerSeriesLimit": 1
            
            }
+ Response 201 (application/json)

            {
                "id": 1,
                "uri": "admin/selling/voucher_series/1"
            }


## Voucher series [/admin/selling/voucher_series/{id}]  
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Voucher series to perform action with. Has example value.

### Read [GET]

+ Response 200 (application/json)
    
        {
                "id": "1",
                "name": "voucher series",
                "codePattern": "Aa",
                "vouchersInSeries": "1",
                "usagesPerVoucherLimit": "1",
                "usagesPerUserLimit": "1",
                "vouchers": [
                    "admin/selling/seller/1"
                ]            
                
            
        }

### Full Update [PUT]
+ Request

    + Header
    
                Authorization: Token {token}

    + Body
    
            {
                "name": "test_name",
                "codePattern": "AA",
                "vouchersInSeries": "1",
                "usagesPerVoucherLimit": "1",
                "usagesPerUserLimit": "1",
                "userPerSeriesLimit": 1
            }

+ Response 204

### Full Update [PATCH]
+ Request

    + Header
    
                Authorization: Token {token}

    + Body
    
            {
                "name": "test_name",
                "codePattern": "AA",
                "vouchersInSeries": "1",
                "usagesPerVoucherLimit": "1",
                "usagesPerUserLimit": "1",
                "userPerSeriesLimit": 1
            
            }
+ Response 204

### Delete [DELETE]
+ Request

    + Header
    
                Authorization: Token {token}
+ Response 204

## Voucher series [/admin/selling/voucher_series/{id}/generate_vouchers]
### Generate vouchers [PUT]

+ Request (application/json)

    + Header
    
                Authorization: Token {token}
        
+ Response 204

## Voucher series [/admin/selling/voucher_series/{id}/export_vouchers]
### Export vouchers [PUT]

+ Request (application/json)

    + Header
    
                Authorization: Token {token}

    + Body
                
                DD
                FF
                
+ Response 200

# Group Admin - Access Token

## Voucher [/admin/user/acces_token]
### Create Voucher [POST]
+ Request (application/json)

    + Header
    
                Authorization: Token {token}
        
    + Body
    
            {
                "user":"1",
        
            }
+ Response 201 (application/json)

            {
                "token": "asdfiopasdjfgiojsdoprj",
            }
