FORMAT: 1A
HOST: http://www.google.com

# Publero API

#### Authorization
To authenticate against the API, client must provide access token in 1 of 3 ways:

- `Authorization` HTTP header in form `Authorization: Token {token}`

- `access_token` query parameter

- `access_token` POST parameter - only for `application/x-www-form-urlencoded` request

Authorization HTTP header is the preferred option.

If authorization fails, status code 403 (Forbidden) is returned automatically with the following response:

```json
{
    "code":403,
    "message":"Access Denied",
     "errors":null
}
```

#### Request fail

If the call was unsuccessful it will return status code 400 (Bad request) and response containing fields (error response):

 - `code` - status code
 
 - `message` - error message (e.g. "Validation Failed")
 
 - `errors` - list of errors


# Group Admin - Publisher
Publisher related links

## Publisher Collection [/admin/publisher]

### List of All Publishers [GET]
+ Request

    + Header
    
                Authorization: Token {token}

+ Response 200 (application/json)

        [
            {
                "name": "Publisher 1",
                "description": "Publisher 1 description",
                "contacts": [
                    {
                        "type": "email",
                        "title": "Personal email",
                        "description": "Email description",
                        "body": "some_email@example.com"
                    },
                    {
                        "type": "address",
                        "title": "Home Address",
                        "description": "Address description",
                        "body": "Some Street 5554, 555 21 Some City"
                    },
                    ...
                ]
            },
            {
                "name": "Publisher 2",
                "description": "Publisher 2 description",
                "contacts": [
                    {
                        "type": "email",
                        "title": "Personal email",
                        "description": "Email description",
                        "body": "some_email@example.com"
                    },
                    {
                        "type": "address",
                        "title": "Home Address",
                        "description": "Address description",
                        "body": "Some Street 5554, 555 21 Some City"
                    },
                    ...
                ]
            },
            ...
        ]

### Create Publisher [POST]
+ Request (application/json)

    + Header
    
                Authorization: Token {token}
        
    + Body
        
                {
                    "name": "Publisher 1",
                    "description": "Publisher 1 description",
                    "contacts": [
                        {
                            "type": "email",
                            "title": "Personal email",
                            "description": "Email description",
                            "body": "some_email@example.com"
                        },
                        {
                            "type": "address",
                            "title": "Home Address",
                            "description": "Address description",
                            "body": "Some Street 5554, 555 21 Some City"
                        },
                        ...
                    ]
                }

+ Response 201 (application/json)

        {
          "id": 1,
          "uri": "/publisher/1"
        }
        
## Publisher [/admin/publisher/{id}]        
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Publisher to perform action with. Has example value.

### Read [GET]
+ Request

    + Header
    
                Authorization: Token {token}
        
+ Response 200 (application/json)

        {
            "name": "Publisher 1",
            "description": "Publisher 1 description",
            "contacts": [
                {
                    "type": "email",
                    "title": "Personal email",
                    "description": "Email description",
                    "body": "some_email@example.com"
                },
                {
                    "type": "address",
                    "title": "Home Address",
                    "description": "Address description",
                    "body": "Some Street 5554, 555 21 Some City"
                },
                ...
            ]

        }
        
### Full Update [PUT]
+ Request (application/json)

    + Header
    
                Authorization: Token {token}
                
    + Body
    
                {
                    "name": "Publisher 1",
                    "description": "Publisher 1 description",
                    "contacts": [
                        {
                            "type": "email",
                            "title": "Personal email",
                            "description": "Email description",
                            "body": "some_email@example.com"
                        },
                        {
                            "type": "address",
                            "title": "Home Address",
                            "description": "Address description",
                            "body": "Some Street 5554, 555 21 Some City"
                        },
                        ...
                    ]
                }    
                
+ Response 204


### Partial Update [PATCH]
+ Request (application/json)

    + Header
    
                Authorization: Token {token}
            
    + Body
    
                {
                    "name": "Publisher 1",
                    "description": "Publisher 1 description",
                    "contacts": [
                        {
                            "type": "email",
                            "title": "Personal email",
                            "description": "Email description",
                            "body": "some_email@example.com"
                        },
                        {
                            "type": "address",
                            "title": "Home Address",
                            "description": "Address description",
                            "body": "Some Street 5554, 555 21 Some City"
                        },
                        ...
                    ]
                }    

+ Response 204

        
### Delete [DELETE]
+ Request

    + Header
    
                Authorization: Token {token}

+ Response 204

# Group Admin - Seller
Seller related links

## Seller Collection [/admin/seller]

### List of All Sellers [GET]
+ Request

    + Header
    
                Authorization: Token {token}

+ Response 200 (application/json)

        [
            {
                "name": "seller 1",
                "description": "seller 1 description",
                "contacts": [
                    {
                        "type": "email",
                        "title": "Personal email",
                        "description": "Email description",
                        "body": "some_email@example.com"
                    },
                    {
                        "type": "address",
                        "title": "Home Address",
                        "description": "Address description",
                        "body": "Some Street 5554, 555 21 Some City"
                    },
                    ...
                ]
            },
            {
                "name": "seller 2",
                "description": "seller 2 description",
                "contacts": [
                    {
                        "type": "email",
                        "title": "Personal email",
                        "description": "Email description",
                        "body": "some_email@example.com"
                    },
                    {
                        "type": "address",
                        "title": "Home Address",
                        "description": "Address description",
                        "body": "Some Street 5554, 555 21 Some City"
                    },
                    ...
                ]
            },
            ...
        ]

### Create Seller [POST]
+ Request (application/json)

    + Header
    
                Authorization: Token {token}
        
    + Body
        
                {
                    "name": "Seller 1",
                    "description": "Seller 1 description",
                    "contacts": [
                        {
                            "type": "email",
                            "title": "Personal email",
                            "description": "Email description",
                            "body": "some_email@example.com"
                        },
                        {
                            "type": "address",
                            "title": "Home Address",
                            "description": "Address description",
                            "body": "Some Street 5554, 555 21 Some City"
                        },
                        ...
                    ]
                }

+ Response 201 (application/json)

        {
          "id": 1,
          "uri": "/seller/1"
        }
        
## Seller [/admin/seller/{id}]        
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the seller to perform action with. Has example value.

### Read [GET]
+ Request

    + Header
    
                Authorization: Token {token}
        
+ Response 200 (application/json)

        {
            "name": "Seller 1",
            "description": "Seller 1 description",
            "contacts": [
                {
                    "type": "email",
                    "title": "Personal email",
                    "description": "Email description",
                    "body": "some_email@example.com"
                },
                {
                    "type": "address",
                    "title": "Home Address",
                    "description": "Address description",
                    "body": "Some Street 5554, 555 21 Some City"
                },
                ...
            ]

        }
        
### Full Update [PUT]
+ Request (application/json)

    + Header
    
                Authorization: Token {token}
                
    + Body

                {
                    "name": "Seller 1",
                    "description": "Seller 1 description",
                    "contacts": [
                        {
                            "type": "email",
                            "title": "Personal email",
                            "description": "Email description",
                            "body": "some_email@example.com"
                        },
                        {
                            "type": "address",
                            "title": "Home Address",
                            "description": "Address description",
                            "body": "Some Street 5554, 555 21 Some City"
                        },
                        ...
                    ]
                }

+ Response 204


### Partial Update [PATCH]
+ Request (application/json)

    + Header
    
                Authorization: Token {token}
                
    + Body
    
                {
                    "name": "Seller 1",
                    "description": "Seller 1 description",
                    "contacts": [
                        {
                            "type": "email",
                            "title": "Personal email",
                            "description": "Email description",
                            "body": "some_email@example.com"
                        },
                        {
                            "type": "address",
                            "title": "Home Address",
                            "description": "Address description",
                            "body": "Some Street 5554, 555 21 Some City"
                        },
                        ...
                    ]
                }

+ Response 204

        
### Delete [DELETE]
+ Request

    + Header
    
                Authorization: Token {token}

+ Response 204